# -*- coding: utf-8 -*-
"""hw3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Pu9YHM6NcXta6Gzg4-7IcAdP8ntlLXD
"""

import turtle

# Set up the turtle
t = turtle.Turtle()

# Draw an octagon
t.forward(100)  # Move forward
t.left(45)      # Turn left by 45 degrees
t.forward(100)
t.left(45)
t.forward(100)
t.left(45)
t.forward(100)
t.left(45)
t.forward(100)
t.left(45)
t.forward(100)
t.left(45)
t.forward(100)
t.left(45)
t.forward(100)
t.left(45)

# Finish drawing
turtle.done()

import turtle

# Set up the turtle
t = turtle.Turtle()

# Draw an octagon using a for loop
for _ in range(8):
    t.forward(100)  # Move forward
    t.left(45)      # Turn left by 45 degrees

# Finish drawing
turtle.done()

import turtle

# Set up the first turtle
turtle1 = turtle.Turtle()
turtle1.color("blue")  # Set the color of the first turtle

# Function to draw a five-pointed star
def draw_star(t):
    for _ in range(5):
        t.forward(100)  # Move forward
        t.right(144)    # Turn right by 144 degrees (not 36 degrees)

# Draw the first star
draw_star(turtle1)

# Set up the second turtle
turtle2 = turtle.Turtle()
turtle2.color("red")  # Set the color of the second turtle
turtle2.penup()        # Lift the pen to move without drawing
turtle2.goto(150, 0)  # Move to a new location
turtle2.pendown()      # Put the pen down to start drawing

# Draw the second star
draw_star(turtle2)

# Finish drawing
turtle.done()

import turtle
import random

# Set up the screen
screen = turtle.Screen()
screen.bgcolor("black")  # Background color

# Set up the turtle
t = turtle.Turtle()
t.speed(0)  # Fastest drawing speed
t.width(2)  # Line width

# Define colors
colors = ["red", "orange", "yellow", "green", "blue", "purple"]

# Function to draw a colorful spiral of squares
def draw_spiral_squares():
    for i in range(100):  # Number of squares
        t.color(random.choice(colors))  # Random color from the list
        t.forward(i * 10)  # Move forward
        t.right(90)  # Turn right 90 degrees
        t.forward(i * 10)  # Move forward again
        t.right(90)  # Turn right 90 degrees
        t.forward(i * 10)  # Move forward again
        t.right(90)  # Turn right 90 degrees
        t.forward(i * 10)  # Complete the square
        t.right(90)  # Turn right 90 degrees to prepare for next square

# Draw the spiral squares
draw_spiral_squares()

# Hide the turtle and finish
t.hideturtle()  # Hide the turtle cursor
turtle.done()  # Keep the window open